version: "3.8"
services:
  app:
    build:
      context: .
      args:
        JAR_FILE: app.jar
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deptmanagement
      SPRING_DATASOURCE_USERNAME: seyunkim
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      AWS_REGION: ap-northeast-2
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deptmanagement
      POSTGRES_USER: seyunkim
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always


volumes:
  pgdata: