name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Build JAR file
        run: ./gradlew build -x test

      - name: Upload JAR file to EC2
        run: |
          scp -i ~/.ssh/deploy_key.pem build/libs/DeptManagement_BackEnd-0.0.1-SNAPSHOT.jar \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/DeptManagement_BackEnd/app.jar

      - name: Upload docker-compose.yml to EC2
        run: |
          scp -i ~/.ssh/deploy_key.pem docker-compose.yml \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/DeptManagement_BackEnd/docker-compose.yml

      - name: Deploy on EC2 (Docker rebuild & run)
        run: |
          ssh -i ~/.ssh/deploy_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/DeptManagement_BackEnd
            docker-compose down
            docker-compose up --build -d
          EOF